#This Dockerfile builds Apache JMeter Master Executable based on juber/jmeter-base
FROM juber/jmeter-base 
LABEL Description="This image is used to start the Apache JMeter Master Executable" 
#Port 60000 required for JMeter Master
EXPOSE 60000
